/*Ci= pipeline de integração continua, sempre que houver git oush essa pipeline vai ser disparada(qualquer push de qualquer branch vai disparar a pipeline)  */
name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2